# Generated by Django 4.1.6 on 2023-02-16 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Продукт')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('start_date', models.DateField(verbose_name='Дата выхода продукта на рынок')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy', models.SmallIntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'ИП')], verbose_name='Звено сети')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Компания')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('house', models.CharField(max_length=10, verbose_name='Дом')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Задолженность')),
                ('date_of_create', models.DateField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='companies', to='network.item')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traders', to='network.link', verbose_name='Поставщик')),
            ],
        ),
    ]
