# Generated by Django 4.1.6 on 2023-02-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Звено сети', 'verbose_name_plural': 'Звенья сети'},
        ),
    ]
