# Generated by Django 4.1.6 on 2023-02-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_item_options_alter_link_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='items',
            field=models.ManyToManyField(related_name='network', to='network.item'),
        ),
    ]
